# Generated by Django 5.2.11 on 2026-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
