# Generated by Django 5.2.11 on 2026-02-09 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('worker', 'Service Provider')], max_length=20)),
                ('service_type', models.CharField(blank=True, choices=[('physical', 'Physical'), ('virtual', 'Virtual')], max_length=20)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert'), ('Master', 'Master')], default='Beginner', max_length=20)),
                ('completed_quests', models.PositiveIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_since', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
